### ISSUE TITLE
Some release ?

### ISSUE THREAD

**Issue by SnailRabbids** [funseek/godot-ios-request-review#1]
@yokochi @funseek
Hello, is it possible to create some release? (For example: https://github.com/godotengine/godot-ios-plugins/releases/tag/3.4-stable)
It will be much more easier to download ready plugin folder with "*.xcframework" folders instead of creating it by ourself.
Because your Instructions steps doesnt work for me :( (I did everything as it should be and got .a files, but it is not enough. Godot cannot recognize this as plugin.)

**Comment by yokochi** [comment]
@SnailRabbids Hello, I will look into ways to make the installation a little easier. Also, when you say that this plugin doesn't work, do you mean that the following Check box does not appear?
<img width="439" alt="Screen Shot 2022-04-30 at 8 02 04" src="https://user-images.githubusercontent.com/545241/166079031-cc97101c-5f45-4904-a93c-58b8e51b73e0.png">
<img width="937" alt="Screen Shot 2022-04-30 at 8 02 42" src="https://user-images.githubusercontent.com/545241/166079036-7578364c-c873-4205-949f-5b80c317968c.png">

**Comment by SnailRabbids** [comment]
@yokochi yep, exactly :( Is it possible for you to create same zip archive with .xcframework as it is in godot-ios-plugins repo? It could help a lot :)

**Comment by SnailRabbids** [comment]
Or mb update some steps. Idk why it doesn't works for me :(

**Comment by yokochi** [comment]
@SnailRabbids Just to confirm, do the files exist below?
ios/plugins/request_review.gdip
ios/plugins/request_review/bin/request_review.debug.a  
ios/plugins/request_review/bin/request_review.release.a

**Comment by SnailRabbids** [comment]
Im not at PC now, but looks like true

**Comment by yokochi** [comment]
@SnailRabbids I don't understand why it is not recognized as a plugin (although it should be if the three files above exist). Do you recognize other plugins? (e.g. https://github.com/godotengine/godot-ios-plugins)

**Comment by SnailRabbids** [comment]
@yokochi Yep, Im using InAppPurchase and it works. Could you send me your .a files? Mb I did something wrong?

**Comment by yokochi** [comment]
@SnailRabbids Uploaded *.a file. Please check it here
https://github.com/funseek/godot-ios-request-review/releases
request_review-v.1.0.0.tgz

**Comment by SnailRabbids** [comment]
@yokochi Thanks, I'll be busy for a few days, but I'll try it ASAP.

**Comment by SnailRabbids** [comment]
@yokochi Same problem. Which version of Godot are you using? (3.4.4.stable)
![image](https://user-images.githubusercontent.com/36141552/166929397-779a42ad-b6e1-4487-a85b-7e40c9c7320a.png)

**Comment by yokochi** [comment]
@SnailRabbids Yes, 3.4.4. but I think you put the gdip file in the wrong place.

wrong
ios/plugins/request_review/request_review.gdip
correct
ios/plugins/request_review.gdip

Please see
https://github.com/funseek/godot-ios-request-review/issues/1#issuecomment-1113858805

**Comment by SnailRabbids** [comment]
@yokochi yep, my bad, sorry for that. Now it works fine :)

**Comment by SnailRabbids** [comment]
I might did same mistake previously.
